package Quests;

public enum QuestObjectiveType {
    KILL_HOSTILE_MOBS,
    KILL_SPECIFIC_MOB,
    KILL_UNIQUE_MOBS,
    VISIT_LOCATION,
    VISIT_UNIQUE_LOCATIONS,

    REACH_WEAPON_LEVEL,
    ENCHANT_WEAPON,
    REACH_ASCENSION,
    SPEND_SKILL_POINTS,
    EARN_SOULS,
    OBTAIN_ARMOR
}
